import type { LanguageCode } from '@/lib/i18n'

const en = {
  home: {
    heroEyebrow: 'Lac, Albania - Est. by the Prela Family',
    heroTitleLine1: 'Marble,',
    heroAccent: 'elevated.',
    heroSubtitle: 'Handcrafted marble accessories for spaces that demand quiet perfection.',
    exploreCollection: 'Explore the Collection',
    ourStory: 'Our Story',
    scroll: 'Scroll',
    curatedSelection: 'Curated Selection',
    featuredPieces: 'Featured Pieces',
    noFeaturedProducts: 'No featured products yet.',
    viewDetails: 'View Details',
    viewAllPieces: 'View all pieces',
    atelierEyebrow: 'The Atelier',
    atelierTitleLine1: 'Carved by hand.',
    atelierTitleLine2: 'Kept forever.',
    atelierTextOne: 'Prela Atelier was born from two brothers and a family legacy in stone. Rooted in Lac, Albania, where natural marble runs through the mountains, we transform raw stone into objects of quiet permanence.',
    atelierTextTwo: 'Every piece passes through the hands of craftspeople trained across generations. We produce in limited quantities, not as a marketing decision, but because quality at scale is a contradiction in stone work.',
    commissionBespoke: 'Commission a Bespoke Piece',
    atelierCardText: 'Sculptural marble objects for curated interiors, penthouses, and gallery spaces across Europe and beyond.',
    stonesEyebrow: 'Our Stones',
    materialsTitle: 'The Materials',
    exploreAllMaterials: 'Explore All Materials',
    trustItems: ['Hand-Selected Stone', 'Free Shipping over 500 EUR', 'Bespoke Commissions', 'Certificate of Authenticity'],
  },
  collections: {
    eyebrow: 'The Complete Range',
    title: 'Collections',
    piecesLabel: (count: number) => `${count} ${count === 1 ? 'piece' : 'pieces'}`,
    noProductsTitle: 'No products yet.',
    noProductsText: 'Check back soon - we are preparing something beautiful.',
    returnHome: 'Return Home',
    viewDetails: 'View Details',
    somethingUnique: 'Something Unique?',
    commissionTitle: 'Commission a bespoke piece',
    commissionText: "Can't find exactly what you're looking for? We create custom marble objects to your exact specifications.",
    beginCommission: 'Begin a Commission',
  },
  materials: {
    eyebrow: 'Our Materials',
    titleLine1: 'The Stone Behind',
    titleLine2: 'the Object',
    intro: 'Every piece we create begins as a slab of authentic natural stone - never composites, never synthetics. Each material carries its own geological story, millions of years in the making.',
    philosophyEyebrow: 'Philosophy',
    philosophyTitleLine1: 'Natural stone.',
    philosophyTitleLine2: 'No exceptions.',
    philosophyTextOne: 'We work exclusively with authentic natural stone. No composites. No engineered surfaces. No artificial coloring. The material as nature produced it - quarried, cut, and refined by hand.',
    philosophyTextTwo: 'Each slab is hand-selected by our team for depth of character, structural integrity, and veining quality. Most are rejected. The ones that pass become Prela Atelier pieces.',
    naturalStone: 'Natural Stone',
    stoneOrigins: 'Stone Origins',
    production: 'Production',
    uniquePieces: 'Unique Pieces',
    rangeEyebrow: 'Our Range',
    rangeTitle: 'Materials We Use',
    noMaterials: 'No materials listed yet.',
    hardness: 'Hardness',
    tone: 'Tone',
    veining: 'Veining',
    careEyebrow: 'Looking After Stone',
    careTitle: 'Care & Maintenance',
    careTips: [
      { title: 'Clean gently', desc: 'Use a soft microfibre cloth and pH-neutral stone cleaner. Never abrasive sponges.' },
      { title: 'Avoid acids', desc: 'Vinegar, lemon juice, and bleach will etch natural stone. Always use stone-specific products.' },
      { title: 'Seal regularly', desc: 'Marble and limestone benefit from sealing every 6-12 months to protect against staining.' },
      { title: "Blot, don't wipe", desc: 'For spills, blot immediately with a dry cloth. Wiping can spread liquid and cause staining.' },
    ],
    fullCareGuide: 'Full Care Guide',
    ctaEyebrow: 'Shop the Collection',
    ctaTitle: 'Experience Stone in Object Form',
    ctaText: 'Each material you see above becomes the objects in our collection. Browse the full range to find a piece that speaks to your space.',
    exploreCollections: 'Explore Collections',
  },
  bespoke: {
    eyebrow: 'Custom Work',
    title: 'Bespoke Commission',
    subtitle: 'We design and craft custom marble pieces to your exact specifications for private clients, interior designers, architects, and gallery spaces.',
    processEyebrow: 'How It Works',
    processTitle: 'The Commission Process',
    process: [
      { step: '01', title: 'Builder', desc: 'Enter dimensions, thickness, quantity, and material so we can create a structured first-pass estimate.' },
      { step: '02', title: 'Review', desc: 'Preview the shape, inspect the calculated quote, and attach your project brief before submitting.' },
      { step: '03', title: 'Consultation', desc: 'We review the structured quote, refine the scope, and confirm the final atelier quotation with you.' },
      { step: '04', title: 'Crafting', desc: 'After approval, the piece moves into production with progress updates and careful delivery planning.' },
    ],
    createEyebrow: 'What We Create',
    createTitle: 'From concept to object, in stone.',
    createText: 'We accept commissions for a wide range of marble objects, from decorative pieces and sculptural tableware to custom furniture components and architectural accents.',
    createItems: ['Custom trays, bowls, and vessels', 'Sculptural centrepieces and decorative objects', 'Monogrammed or branded pieces for businesses', 'Architectural details, thresholds, panels, and shelves', 'Wedding gifts and anniversary pieces', 'Interior designer commissions'],
    timelineEyebrow: 'A Note on Timelines',
    timelineTitle: 'Crafted with patience. Delivered with precision.',
    timelineText: 'Bespoke pieces typically require 4 to 8 weeks from approval to delivery, depending on complexity and stone availability. Rush commissions may be accommodated, please mention your timeline when enquiring.',
    estimatesLabel: 'Structured estimates',
    estimatesText: 'Based on area, quantity, material, and atelier production settings.',
    builderEyebrow: 'Begin Your Commission',
    builderTitle: 'Builder + Enquiry',
  },
  product: {
    backToCollections: 'Back to Collections',
    defaultEyebrow: 'Prela Atelier - Natural Stone Object',
    stoneProperties: 'Stone Properties',
    hardness: 'Hardness',
    tone: 'Tone',
    veining: 'Veining',
    learnMoreAbout: (material: string) => `Learn more about ${material}`,
    freeShippingOver: (amount: string) => `Free shipping on orders over ${amount}`,
    estimatedDelivery: 'Estimated delivery: 5-7 business days',
    certificateIncluded: 'Includes stone documentation & certificate of authenticity',
  },
  orderConfirmed: {
    notFound: 'Order not found.',
    returnHome: 'Return Home',
    thankYou: (firstName: string) => `Thank you, ${firstName}.`,
    preparing: 'Your order has been received and is being prepared with care.',
    orderReference: 'Order Reference',
    confirmationSent: (email: string) => `A confirmation will be sent to ${email}`,
    orderSummary: 'Order Summary',
    shipping: 'Shipping',
    free: 'Free',
    total: 'Total',
    trackYourOrder: 'Track Your Order',
    continueShopping: 'Continue Shopping',
    trackAnytime: 'Track your order anytime using your order code and email at',
    trackingPage: 'our tracking page',
  },
}

const sq = {
  home: {
    heroEyebrow: 'Lac, Shqiperi - Themeluar nga familja Prela',
    heroTitleLine1: 'Mermeri,',
    heroAccent: 'i ngritur.',
    heroSubtitle: 'Aksesore mermeri te punuar me dore per hapesira qe kerkojne persosmeri te qete.',
    exploreCollection: 'Eksploro Koleksionin',
    ourStory: 'Historia Jone',
    scroll: 'Leviz',
    curatedSelection: 'Perzgjedhje e Kuruar',
    featuredPieces: 'Pjeset Kryesore',
    noFeaturedProducts: 'Nuk ka ende produkte te vecuara.',
    viewDetails: 'Shiko Detajet',
    viewAllPieces: 'Shiko te gjitha pjeset',
    atelierEyebrow: 'Atelieja',
    atelierTitleLine1: 'I gdhendur me dore.',
    atelierTitleLine2: 'Per t\'u mbajtur pergjithmone.',
    atelierTextOne: 'Prela Atelier lindi nga dy vellazer dhe nje trashegimi familjare ne gur. E rrenjosur ne Lac, Shqiperi, ne e shnderrrojme gurin e papershtatur ne objekte me qendrueshmeri te qete.',
    atelierTextTwo: 'Cdo pjese kalon ne duart e mjeshterve te trajnuar brez pas brezi. Ne prodhojme ne sasi te kufizuara sepse cilesia ne shkalle te gjere bie ndesh me punen ne gur.',
    commissionBespoke: 'Kerko nje Pjese me Porosi',
    atelierCardText: 'Objekte skulpturore mermeri per interiere te kuruara, penthouse dhe hapesira galerie ne Europe e me gjere.',
    stonesEyebrow: 'Guret Tane',
    materialsTitle: 'Materialet',
    exploreAllMaterials: 'Shiko te Gjitha Materialet',
    trustItems: ['Gur i zgjedhur me dore', 'Transport falas mbi 500 EUR', 'Porosi te personalizuara', 'Certifikate autenticiteti'],
  },
  collections: {
    eyebrow: 'Gama e Plote',
    title: 'Koleksione',
    piecesLabel: (count: number) => `${count} ${count === 1 ? 'pjese' : 'pjese'}`,
    noProductsTitle: 'Nuk ka ende produkte.',
    noProductsText: 'Rikthehuni shpejt - po pergatisim dicka te bukur.',
    returnHome: 'Kthehu ne Faqen Kryesore',
    viewDetails: 'Shiko Detajet',
    somethingUnique: 'Dicka Unike?',
    commissionTitle: 'Porosit nje pjese me porosi',
    commissionText: 'Nuk po gjeni pikerisht ate qe kerkoni? Ne krijojme objekte mermeri sipas specifikimeve tuaja te sakta.',
    beginCommission: 'Nis nje Porosi',
  },
  materials: {
    eyebrow: 'Materialet Tona',
    titleLine1: 'Guri Pas',
    titleLine2: 'Objektit',
    intro: 'Cdo pjese qe krijojme nis si nje pllake guri natyral autentik - kurre kompozite, kurre sintetike. Cdo material mbart historine e vet gjeologjike.',
    philosophyEyebrow: 'Filozofia',
    philosophyTitleLine1: 'Gur natyral.',
    philosophyTitleLine2: 'Pa perjashtime.',
    philosophyTextOne: 'Ne punojme vetem me gur natyral autentik. Pa kompozite. Pa siperfaqe te inxhinieruara. Materiali si e ka prodhuar natyra - i nxjerre, i prere dhe i perfunduar me dore.',
    philosophyTextTwo: 'Cdo pllake perzgjidhet me dore per karakter, integritet strukturor dhe cilesi te damarimit. Ato qe kalojne behen pjese te Prela Atelier.',
    naturalStone: 'Gur Natyral',
    stoneOrigins: 'Origjina Guresh',
    production: 'Prodhim',
    uniquePieces: 'Pjese Unike',
    rangeEyebrow: 'Gama Jone',
    rangeTitle: 'Materialet qe Perdorem',
    noMaterials: 'Nuk ka ende materiale te listuara.',
    hardness: 'Fortesia',
    tone: 'Toni',
    veining: 'Damarimi',
    careEyebrow: 'Kujdesi per Gurin',
    careTitle: 'Kujdes & Mirembajtje',
    careTips: [
      { title: 'Pastrojeni bute', desc: 'Perdorni cope mikrofiber dhe pastrues me pH neutral. Kurre sfungjere abrazive.' },
      { title: 'Shmangni acidet', desc: 'Uthulla, limoni dhe zbardhuesi mund te demtojne gurin natyral.' },
      { title: 'Izolojeni rregullisht', desc: 'Mermeri dhe guri gelqeror perfitojne nga izolimi cdo 6-12 muaj.' },
      { title: 'Thithni, mos fshini', desc: 'Per derdhjet, thithni menjehere me cope te thate per te shmangur njollat.' },
    ],
    fullCareGuide: 'Udhezuesi i Plote i Kujdesit',
    ctaEyebrow: 'Shiko Koleksionin',
    ctaTitle: 'Perjeto Gurin ne Forme Objekti',
    ctaText: 'Cdo material qe shihni me siper shnderrohet ne objektet e koleksionit tone. Shikoni gamen e plote per te gjetur nje pjese per hapesiren tuaj.',
    exploreCollections: 'Shiko Koleksionet',
  },
  bespoke: {
    eyebrow: 'Pune te Personalizuara',
    title: 'Porosi me Porosi',
    subtitle: 'Ne projektojme dhe krijojme pjese mermeri te personalizuara sipas specifikimeve tuaja per kliente privat, dizajnere interieri, arkitekte dhe hapesira galerie.',
    processEyebrow: 'Si Funksionon',
    processTitle: 'Procesi i Porosise',
    process: [
      { step: '01', title: 'Ndertuesi', desc: 'Vendosni permasat, trashesine, sasine dhe materialin per nje vleresim fillestar te strukturuar.' },
      { step: '02', title: 'Rishikimi', desc: 'Shikoni formen, kontrolloni oferten e llogaritur dhe dergoni pershkrimin e projektit.' },
      { step: '03', title: 'Konsultimi', desc: 'Ne shqyrtojme oferten, rafinojme kerkesen dhe konfirmojme oferten finale.' },
      { step: '04', title: 'Punimi', desc: 'Pas miratimit, pjesa kalon ne prodhim me perditesime mbi progresin dhe dorezimin.' },
    ],
    createEyebrow: 'Cfare Krijojme',
    createTitle: 'Nga koncepti te objekti, ne gur.',
    createText: 'Pranojme porosi per objekte dekorative, artikuj skulpturore tavoline, komponente mobiljesh dhe elemente arkitekturore.',
    createItems: ['Tabaka, tasa dhe ene te personalizuara', 'Qenderpjese skulpturore dhe objekte dekorative', 'Pjese me monogram ose markim per biznese', 'Detaje arkitekturore, pragje, panele dhe rafte', 'Dhurata dasmash dhe pervjetoresh', 'Porosi nga dizajnere interieri'],
    timelineEyebrow: 'Shenim per Afatet',
    timelineTitle: 'I punuar me durim. I dorezuar me precizion.',
    timelineText: 'Pjeset me porosi zakonisht kerkojne 4 deri ne 8 jave nga miratimi deri ne dorezim, ne varesi te kompleksitetit dhe disponueshmerise se gurit.',
    estimatesLabel: 'Vleresime te strukturuara',
    estimatesText: 'Bazuar ne siperfaqe, sasi, material dhe rregullimet e prodhimit te ateliese.',
    builderEyebrow: 'Nis Porosine Tuaj',
    builderTitle: 'Ndertues + Kerkese',
  },
  product: {
    backToCollections: 'Kthehu te Koleksionet',
    defaultEyebrow: 'Prela Atelier - Objekt guri natyral',
    stoneProperties: 'Karakteristikat e Gurit',
    hardness: 'Fortesia',
    tone: 'Toni',
    veining: 'Damarimi',
    learnMoreAbout: (material: string) => `Meso me shume per ${material}`,
    freeShippingOver: (amount: string) => `Dergese falas per porosi mbi ${amount}`,
    estimatedDelivery: 'Dergese e vleresuar: 5-7 dite pune',
    certificateIncluded: 'Perfshin dokumentacionin e gurit dhe certifikaten e autenticitetit',
  },
  orderConfirmed: {
    notFound: 'Porosia nuk u gjet.',
    returnHome: 'Kthehu ne Faqen Kryesore',
    thankYou: (firstName: string) => `Faleminderit, ${firstName}.`,
    preparing: 'Porosia juaj u pranua dhe po pergatitet me kujdes.',
    orderReference: 'Referenca e Porosise',
    confirmationSent: (email: string) => `Konfirmimi do te dergohet te ${email}`,
    orderSummary: 'Permbledhja e Porosise',
    shipping: 'Dergesa',
    free: 'Falas',
    total: 'Totali',
    trackYourOrder: 'Gjurmo Porosine',
    continueShopping: 'Vazhdo Blerjen',
    trackAnytime: 'Gjurmojeni porosine ne cdo kohe duke perdorur kodin e porosise dhe emailin tek',
    trackingPage: 'faqja jone e gjurmimit',
  },
}

export function getPublicPageCopy(language: LanguageCode) {
  return language === 'sq' ? sq : en
}
